{
 "title": "NiFi",
 "description": "Complete dashboard using metrics from prometheus JMX exporter, with drill down per NiFi release > pod",
 "tags": [
  "JVM",
  "nifi"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(jvm_pool_stats, exported_instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Heap used",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_heap_stats{status=\"used\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 9, "y": 0 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{job=\"prometheus_pushgateway\"})*1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "avg(jvm_general_stats{status=\"uptime\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "PS Eden Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "jvm_pool_stats{status=\"mem_pool_ps_eden_space\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "PS Old Gen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "jvm_pool_stats{status=\"mem_pool_ps_old_gen\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "PS Survivor Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "jvm_pool_stats{status=\"mem_pool_ps_survivor_space\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "jvm_pool_stats{status=\"mem_pool_metaspace\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "jvm_pool_stats{status=\"mem_pool_compressed_class_space\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "jvm_pool_stats{status=\"mem_pool_code_cache\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_group_amount_threads_total{status=\"nano\"}",
     "legendFormat": "JVM current threads  {{exported_instance}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_stats{status=\"ps_marksweep_runs\"}",
     "legendFormat": "{{status}} {{exported_instance}}"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_stats{status=\"ps_marksweep_runs\"}[5m])",
     "legendFormat": "{{status}} {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"prometheus_pushgateway\"}"
    }
   ]
  }
 ]
}