{
 "title": "Openshift cluster",
 "description": "Monitors Openshift/k8s cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [
  "kubernetes",
  "openshift"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster - CPU usage (5m avg)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Master - CPU usage (5m avg)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node_role_kubernetes_io_master=\"true\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) / sum (machine_cpu_cores{node_role_kubernetes_io_master=\"true\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Registry - CPU usage (5m avg)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node_role_kubernetes_io_registry=\"true\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) / sum (machine_cpu_cores{node_role_kubernetes_io_registry=\"true\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Infra - CPU usage (5m avg)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node_role_kubernetes_io_infra=\"true\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) / sum (machine_cpu_cores{node_role_kubernetes_io_infra=\"true\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "App - CPU usage (5m avg)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node_role_kubernetes_io_compute=\"true\",kubernetes_io_hostname=~\"^$Node$\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) / sum (machine_cpu_cores{node_role_kubernetes_io_compute=\"true\"}) * 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_master=\"true\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_master=\"true\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_registry=\"true\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_registry=\"true\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 16, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_infra=\"true\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_infra=\"true\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_compute=\"true\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_compute=\"true\"})"
      }
     ]
    },
    {
     "title": "Cluster - memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Master - Memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 9 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node_role_kubernetes_io_master=\"true\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{node_role_kubernetes_io_master=\"true\",kubernetes_io_hostname=~\"^$Node$\"})* 100"
      }
     ]
    },
    {
     "title": "Registry - Memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 9 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node_role_kubernetes_io_registry=\"true\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{node_role_kubernetes_io_registry=\"true\",kubernetes_io_hostname=~\"^$Node$\"})* 100"
      }
     ]
    },
    {
     "title": "Infra - Memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 9 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node_role_kubernetes_io_infra=\"true\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{node_role_kubernetes_io_infra=\"true\",kubernetes_io_hostname=~\"^$Node$\"})* 100"
      }
     ]
    },
    {
     "title": "App - Memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node_role_kubernetes_io_compute=\"true\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{node_role_kubernetes_io_compute=\"true\",kubernetes_io_hostname=~\"^$Node$\"})* 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 14 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 14 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_master=\"true\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 14 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_master=\"true\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 14 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_registry=\"true\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 14 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_registry=\"true\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 16, "y": 14 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_infra=\"true\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 14 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_infra=\"true\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 14 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_compute=\"true\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 14 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_compute=\"true\"})"
      }
     ]
    },
    {
     "title": "Cluster - Root volume filesystem usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Master - Root volume filesystem",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 17 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{node_role_kubernetes_io_master=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{node_role_kubernetes_io_master=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Registry - Root volume filesystem",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 17 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{node_role_kubernetes_io_registry=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{node_role_kubernetes_io_registry=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Infra - Root volume filesystem",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 17 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{node_role_kubernetes_io_infra=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{node_role_kubernetes_io_infra=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "App - Root volume filesystem",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 17 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{node_role_kubernetes_io_compute=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{node_role_kubernetes_io_compute=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 22 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 22 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 22 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_master=\"true\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 22 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_master=\"true\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 22 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_registry=\"true\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 22 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_registry=\"true\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 16, "y": 22 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_infra=\"true\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 22 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_infra=\"true\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 22 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_compute=\"true\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 22 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_compute=\"true\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Master - CPU usage (5m avg)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node_role_kubernetes_io_master=\"true\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) / sum (machine_cpu_cores{node_role_kubernetes_io_master=\"true\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Registry - CPU usage (5m avg)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node_role_kubernetes_io_registry=\"true\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) / sum (machine_cpu_cores{node_role_kubernetes_io_registry=\"true\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Infra - CPU usage (5m avg)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node_role_kubernetes_io_infra=\"true\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) / sum (machine_cpu_cores{node_role_kubernetes_io_infra=\"true\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "App - CPU usage (5m avg)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node_role_kubernetes_io_compute=\"true\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) / sum (machine_cpu_cores{node_role_kubernetes_io_compute=\"true\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_master=\"true\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_master=\"true\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_registry=\"true\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_registry=\"true\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_infra=\"true\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_infra=\"true\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_compute=\"true\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_compute=\"true\"})"
      }
     ]
    },
    {
     "title": "Master - CPU usage by host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_master=\"true\"}[5m])) by (kubernetes_io_hostname)",
       "legendFormat": "{{kubernetes_io_hostname}}"
      }
     ]
    },
    {
     "title": "Registry - CPU usage by host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_registry=\"true\"}[5m])) by (kubernetes_io_hostname)",
       "legendFormat": "{{kubernetes_io_hostname}}"
      }
     ]
    },
    {
     "title": "Infra - CPU usage by host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{name=~\"^k8s_.*\",node_role_kubernetes_io_infra=\"true\"}[5m])) by (kubernetes_io_hostname)",
       "legendFormat": "{{kubernetes_io_hostname}}"
      }
     ]
    },
    {
     "title": "App - CPU usage by host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_compute=\"true\"}[5m])) by (kubernetes_io_hostname)",
       "legendFormat": "{{kubernetes_io_hostname}}"
      }
     ]
    },
    {
     "title": "Master - CPU usage by process",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",node_role_kubernetes_io_master=\"true\"}[5m])) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "Registry - CPU usage by process",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",node_role_kubernetes_io_registry=\"true\"}[5m])) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "Infra - CPU usage by process",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",node_role_kubernetes_io_infra=\"true\"}[5m])) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "App - CPU usage by process",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",node_role_kubernetes_io_compute=\"true\"}[5m])) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "Master - CPU usage by namespace",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_master=\"true\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}[5m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Registry - CPU usage by namespace",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_registry=\"true\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}[5m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Infra - CPU usage by namespace",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_infra=\"true\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}[5m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "App - CPU usage by namespace",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_compute=\"true\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}[5m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Master - CPU usage by Pod|Container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",node_role_kubernetes_io_master=\"true\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (container_name, pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      }
     ]
    },
    {
     "title": "Registry - CPU usage by Pod|Container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",node_role_kubernetes_io_registry=\"true\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (container_name, pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      }
     ]
    },
    {
     "title": "Infra - CPU usage by Pod|Container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",node_role_kubernetes_io_infra=\"true\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (container_name, pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      }
     ]
    },
    {
     "title": "App - CPU usage by Pod|Container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",node_role_kubernetes_io_compute=\"true\"}[5m])) by (namespace,container_name, pod_name)",
       "legendFormat": "{{namespace}} | pod: {{ pod_name }} | {{ container_name }}"
      }
     ]
    },
    {
     "title": "Master - CPU usage by container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_master=\"true\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}[5m])) by (container_name)",
       "legendFormat": "{{container_name}}"
      }
     ]
    },
    {
     "title": "Registry - CPU usage by container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 40 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_registry=\"true\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}[5m])) by (container_name)",
       "legendFormat": "{{container_name}}"
      }
     ]
    },
    {
     "title": "Infra - CPU usage by container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_infra=\"true\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}[5m])) by (container_name)",
       "legendFormat": "{{container_name}}"
      }
     ]
    },
    {
     "title": "App - CPU usage by container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 40 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_compute=\"true\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}[5m])) by (namespace,container_name)",
       "legendFormat": "{{namespace}} | {{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Master - Memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node_role_kubernetes_io_master=\"true\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{node_role_kubernetes_io_master=\"true\",kubernetes_io_hostname=~\"^$Node$\"})* 100"
      }
     ]
    },
    {
     "title": "Registry - Memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node_role_kubernetes_io_registry=\"true\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{node_role_kubernetes_io_registry=\"true\",kubernetes_io_hostname=~\"^$Node$\"})* 100"
      }
     ]
    },
    {
     "title": "Infra - Memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 3 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node_role_kubernetes_io_infra=\"true\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{node_role_kubernetes_io_infra=\"true\",kubernetes_io_hostname=~\"^$Node$\"})* 100"
      }
     ]
    },
    {
     "title": "App - Memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 3 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node_role_kubernetes_io_compute=\"true\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{node_role_kubernetes_io_compute=\"true\",kubernetes_io_hostname=~\"^$Node$\"})* 100"
      }
     ]
    },
    {
     "title": "Master - Memory usage by host",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{id=\"/\",node_role_kubernetes_io_master=\"true\",container_name!=\"POD\"}",
       "legendFormat": "{{instance}}"
      },
      {}
     ]
    },
    {
     "title": "Registry - Memory usage by host",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{id=\"/\",node_role_kubernetes_io_registry=\"true\",container_name!=\"POD\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Infra - Memory usage by host",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{id=\"/\",node_role_kubernetes_io_infra=\"true\",container_name!=\"POD\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "App - Memory usage by host",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{id=\"/\",node_role_kubernetes_io_compute=\"true\",container_name!=\"POD\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Master - Processes memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",node_role_kubernetes_io_master=\"true\"}) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "Registry - Processes memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",node_role_kubernetes_io_registry=\"true\"}) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "Infra - Processes memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",node_role_kubernetes_io_infra=\"true\"}) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "App - Processes memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",node_role_kubernetes_io_compute=\"true\"}) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "Master - Memory usage by namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_master=\"true\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Registry - Memory usage by namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_registry=\"true\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Infra - Memory usage by namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_infra=\"true\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "App - Memory usage by namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_compute=\"true\",container_name!=\"POD\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Master - Memory usage by pod:container",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_master=\"true\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}) by (container_name,pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      }
     ]
    },
    {
     "title": "Registry - Memory usage by pod:container",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 27 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_registry=\"true\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}) by (container_name,pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      }
     ]
    },
    {
     "title": "Infra - Memory usage by pod:container",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_infra=\"true\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}) by (container_name,pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      }
     ]
    },
    {
     "title": "App - Memory usage by pod:container",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 27 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_compute=\"true\",container_name!=\"POD\"}) by (namespace,container_name,pod_name)",
       "legendFormat": "{{namespace}} | pod: {{ pod_name }} | {{ container_name }}"
      }
     ]
    },
    {
     "title": "Master - Memory usage by container",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_master=\"true\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}) by (namespace,container_name)",
       "legendFormat": "{{namespace}} | {{container_name}}"
      }
     ]
    },
    {
     "title": "Registry - Memory usage by container",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_registry=\"true\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}) by (namespace,container_name)",
       "legendFormat": "{{namespace}} | {{container_name}}"
      }
     ]
    },
    {
     "title": "Infra - Memory usage by container",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_infra=\"true\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}) by (namespace,container_name)",
       "legendFormat": "{{namespace}} | {{container_name}}"
      }
     ]
    },
    {
     "title": "App - Memory usage by container",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",node_role_kubernetes_io_compute=\"true\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}) by (namespace,container_name)",
       "legendFormat": "{{namespace}} | {{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "File system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Master - Root volume filesystem",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{container_name=\"\",node_role_kubernetes_io_master=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{container_name=\"\",node_role_kubernetes_io_master=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Registry - Root volume filesystem",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 4 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{node_role_kubernetes_io_registry=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{node_role_kubernetes_io_registry=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Infra - Root volume filesystem",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 4 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{node_role_kubernetes_io_infra=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{node_role_kubernetes_io_infra=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "App - Root volume filesystem",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{node_role_kubernetes_io_compute=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{node_role_kubernetes_io_compute=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Used Root Volume",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_master=\"true\"})"
      }
     ]
    },
    {
     "title": "Total Root Volume",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_master=\"true\"})"
      }
     ]
    },
    {
     "title": "Used Root Volume",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_registry=\"true\"})"
      }
     ]
    },
    {
     "title": "Total Root Volume",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_registry=\"true\"})"
      }
     ]
    },
    {
     "title": "Used Root Volume",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 9 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_infra=\"true\"})"
      }
     ]
    },
    {
     "title": "Total Root Volume",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 9 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_infra=\"true\"})"
      }
     ]
    },
    {
     "title": "Used Root Volume",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 9 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_compute=\"true\"})"
      }
     ]
    },
    {
     "title": "Total Root Volume",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 9 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_compute=\"true\"})"
      }
     ]
    },
    {
     "title": "Master - Root volume file system",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_usage_bytes{container_name=\"\",node_role_kubernetes_io_master=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\"}",
       "legendFormat": "Usage: {{instance}}"
      },
      {
       "expr": "container_fs_limit_bytes{container_name=\"\",node_role_kubernetes_io_master=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root\"}",
       "legendFormat": "Limit: {{instance}}"
      }
     ]
    },
    {
     "title": "Registry - Root volume file system",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_usage_bytes{node_role_kubernetes_io_registry=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\"}",
       "legendFormat": "Usage: {{instance}}"
      },
      {
       "expr": "container_fs_limit_bytes{node_role_kubernetes_io_registry=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\"}",
       "legendFormat": "Limit: {{instance}}"
      }
     ]
    },
    {
     "title": "Infra - Root volume file system",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_usage_bytes{node_role_kubernetes_io_infra=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\"}",
       "legendFormat": "Usage: {{instance}}"
      }
     ]
    },
    {
     "title": "App - Root volume file system",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_usage_bytes{node_role_kubernetes_io_compute=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\"}",
       "legendFormat": "Usage: {{instance}}"
      },
      {
       "expr": "container_fs_limit_bytes{node_role_kubernetes_io_compute=\"true\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\"}",
       "legendFormat": "Limit: {{instance}}"
      }
     ]
    },
    {
     "title": "Master - Var01 file system",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_usage_bytes{node_role_kubernetes_io_master=\"true\",device=~\"^/dev/mapper/VolGroup.*_Var01\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}",
       "legendFormat": "Usage: {{instance}}"
      },
      {
       "expr": "container_fs_limit_bytes{node_role_kubernetes_io_master=\"true\",device=~\"^/dev/mapper/VolGroup.*_Var01\",kubernetes_io_hostname=~\"^$Node$\"}",
       "legendFormat": "Limit: {{instance}}"
      }
     ]
    },
    {
     "title": "Registry - Var01 file system",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_usage_bytes{node_role_kubernetes_io_registry=\"true\",device=~\"^/dev/mapper/VolGroup.*_Var01\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}",
       "legendFormat": "Usage: {{instance}}"
      },
      {
       "expr": "container_fs_limit_bytes{node_role_kubernetes_io_registry=\"true\",device=~\"^/dev/mapper/VolGroup.*_Var01\",kubernetes_io_hostname=~\"^$Node$\"}",
       "legendFormat": "Limit: {{instance}}"
      }
     ]
    },
    {
     "title": "Infra - Var01 file system",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_usage_bytes{node_role_kubernetes_io_infra=\"true\",device=~\"^/dev/mapper/VolGroup.*_Var01\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}",
       "legendFormat": "Usage: {{instance}}"
      },
      {
       "expr": "container_fs_limit_bytes{node_role_kubernetes_io_infra=\"true\",device=~\"^/dev/mapper/VolGroup.*_Var01\",kubernetes_io_hostname=~\"^$Node$\"}",
       "legendFormat": "Limit: {{instance}}"
      }
     ]
    },
    {
     "title": "Registry - Var01 file system",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_usage_bytes{node_role_kubernetes_io_registry=\"true\",device=~\"^/dev/mapper/VolGroup.*_Var01\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}",
       "legendFormat": "Usage: {{instance}}"
      },
      {
       "expr": "container_fs_limit_bytes{node_role_kubernetes_io_registry=\"true\",device=~\"^/dev/mapper/VolGroup.*_Var01\",kubernetes_io_hostname=~\"^$Node$\"}",
       "legendFormat": "Limit: {{instance}}"
      }
     ]
    },
    {
     "title": "Master - Var02 file system",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_usage_bytes{node_role_kubernetes_io_master=\"true\",device=~\"^/dev/mapper/VolGroup.*_Var02\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}",
       "legendFormat": "Usage: {{instance}}"
      },
      {
       "expr": "container_fs_limit_bytes{node_role_kubernetes_io_master=\"true\",device=~\"^/dev/mapper/VolGroup.*_Var02\",kubernetes_io_hostname=~\"^$Node$\"}",
       "legendFormat": "Limit: {{instance}}"
      }
     ]
    },
    {
     "title": "Registry - Var02 file system",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_usage_bytes{node_role_kubernetes_io_registry=\"true\",device=~\"^/dev/mapper/VolGroup.*_Var02\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}",
       "legendFormat": "Usage: {{instance}}"
      },
      {
       "expr": "container_fs_limit_bytes{node_role_kubernetes_io_registry=\"true\",device=~\"^/dev/mapper/VolGroup.*_Var02\",kubernetes_io_hostname=~\"^$Node$\"}",
       "legendFormat": "Limit: {{instance}}"
      }
     ]
    },
    {
     "title": "Infra - Var02 file system",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_usage_bytes{node_role_kubernetes_io_infra=\"true\",device=~\"^/dev/mapper/VolGroup.*_Var02\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}",
       "legendFormat": "Usage: {{instance}}"
      },
      {
       "expr": "container_fs_limit_bytes{node_role_kubernetes_io_infra=\"true\",device=~\"^/dev/mapper/VolGroup.*_Var02\",kubernetes_io_hostname=~\"^$Node$\"}",
       "legendFormat": "Limit: {{instance}}"
      }
     ]
    },
    {
     "title": "App - Var02 file system",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_usage_bytes{node_role_kubernetes_io_compute=\"true\",device=~\"^/dev/mapper/VolGroup.*_Var02\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}",
       "legendFormat": "Usage: {{instance}}"
      },
      {
       "expr": "container_fs_limit_bytes{node_role_kubernetes_io_compute=\"true\",device=~\"^/dev/mapper/VolGroup.*_Var02\",kubernetes_io_hostname=~\"^$Node$\"}",
       "legendFormat": "Limit: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster - Network I/O pressure",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[5m]))",
       "legendFormat": "Received"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[5m]))",
       "legendFormat": "Sent"
      }
     ]
    },
    {
     "title": "Master - Network I/O pressure",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_master=\"true\"}[5m]))",
       "legendFormat": "Received"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_master=\"true\"}[5m]))",
       "legendFormat": "Sent"
      }
     ]
    },
    {
     "title": "Registry - Network I/O pressure",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_registry=\"true\"}[5m]))",
       "legendFormat": "Received"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_registry=\"true\"}[5m]))",
       "legendFormat": "Sent"
      }
     ]
    },
    {
     "title": "Infra - Network I/O pressure",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_infra=\"true\"}[5m]))",
       "legendFormat": "Received"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_infra=\"true\"}[5m]))",
       "legendFormat": "Sent"
      }
     ]
    },
    {
     "title": "App - Network I/O pressure",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_compute=\"true\"}[5m]))",
       "legendFormat": "Received"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\", node_role_kubernetes_io_compute=\"true\"}[5m]))",
       "legendFormat": "Sent"
      }
     ]
    },
    {
     "title": "All processes network I/O (5m avg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (id)",
       "legendFormat": "-> {{ id }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (id)",
       "legendFormat": "<- {{ id }}"
      }
     ]
    },
    {
     "title": "Master - Processes network I/O (5m avg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",node_role_kubernetes_io_master=\"true\"}[5m])) by (id)",
       "legendFormat": "-> {{ id }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",node_role_kubernetes_io_master=\"true\"}[5m])) by (id)",
       "legendFormat": "<- {{ id }}"
      }
     ]
    },
    {
     "title": "Registry - Processes network I/O (5m avg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",node_role_kubernetes_io_registry=\"true\"}[5m])) by (id)",
       "legendFormat": "-> {{ id }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",node_role_kubernetes_io_registry=\"true\"}[5m])) by (id)",
       "legendFormat": "<- {{ id }}"
      }
     ]
    },
    {
     "title": "Infra - Processes network I/O (5m avg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",node_role_kubernetes_io_infra=\"true\"}[5m])) by (id)",
       "legendFormat": "-> {{ id }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",node_role_kubernetes_io_infra=\"true\"}[5m])) by (id)",
       "legendFormat": "<- {{ id }}"
      }
     ]
    },
    {
     "title": "App - Processes network I/O (5m avg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",node_role_kubernetes_io_compute=\"true\"}[5m])) by (id)",
       "legendFormat": "-> {{ id }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",node_role_kubernetes_io_compute=\"true\"}[5m])) by (id)",
       "legendFormat": "<- {{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application Pod limit",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 6 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "1/((sum(machine_cpu_cores{node_role_kubernetes_io_master!=\"true\",node_role_kubernetes_io_infra!=\"true\"})*10) / sum(kubelet_running_pod_count))  * 100 "
      }
     ]
    },
    {
     "title": "Maximum Number of Pods allowed on App Nodes",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 5, "x": 13, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(machine_cpu_cores{node_role_kubernetes_io_master!=\"true\",node_role_kubernetes_io_infra!=\"true\"})*10"
      }
     ]
    },
    {
     "title": "Current number of Running App Pods",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kubelet_running_pod_count{node_role_kubernetes_io_master!=\"true\",node_role_kubernetes_io_infra!=\"true\"})"
      }
     ]
    },
    {
     "title": "Pods per node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (kubelet_running_pod_count) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Pods CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (namespace,pod_name)",
       "legendFormat": "{{namespace}}->{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Pods memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}) by (namespace,pod_name)",
       "legendFormat": "{{namespace}}->{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Pods network I/O (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (namespace,pod_name)",
       "legendFormat": "{{namespace}}-> {{ pod_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (namespace,pod_name)",
       "legendFormat": "{{namespace}}<- {{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers per node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (kubelet_running_container_count) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Containers CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"$Node$\"}[5m])) by (namespace,container_name, pod_name)",
       "legendFormat": "{{namespace}}->pod: {{ pod_name }} | {{ container_name }}"
      }
     ]
    },
    {
     "title": "Containers memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}) by (namespace,container_name, pod_name)",
       "legendFormat": "{{namespace}}->pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}) by (namespace,kubernetes_io_hostname, name, image)",
       "legendFormat": "{{namespace}}->docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}) by (namespace,kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "{{namespace}}->rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      }
     ]
    },
    {
     "title": "Containers network I/O (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (namespace,container_name, pod_name)",
       "legendFormat": "{{namespace}}-> pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (namespace,container_name, pod_name)",
       "legendFormat": "{{namespace}}<- pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (namespace,kubernetes_io_hostname, name, image)",
       "legendFormat": "{{namespace}}-> docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (namespace,kubernetes_io_hostname, name, image)",
       "legendFormat": "{{namespace}}<- docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (namespace,kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "{{namespace}}-> rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (namespace,kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "{{namespace}}<- rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  }
 ]
}