{
 "title": "Openshift cluster",
 "description": "Monitors Openshift/k8s cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [
  "kubernetes",
  "openshift"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster - CPU usage (5m avg)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Master - CPU usage (5m avg)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",region=\"master\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) / sum (machine_cpu_cores{region=\"master\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Registry - CPU usage (5m avg)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",region=\"registry\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) / sum (machine_cpu_cores{region=\"registry\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Infra - CPU usage (5m avg)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",region=\"infra\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) / sum (machine_cpu_cores{region=\"infra\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "App - CPU usage (5m avg)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",region=\"apps\",kubernetes_io_hostname=~\"^$Node$\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) / sum (machine_cpu_cores{region=\"apps\"}) * 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"master\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\", region=\"master\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"registry\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\", region=\"registry\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 16, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"infra\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\", region=\"infra\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"apps\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\", region=\"apps\"})"
      }
     ]
    },
    {
     "title": "Cluster - memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Master - Memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 9 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",region=\"master\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{region=\"master\",kubernetes_io_hostname=~\"^$Node$\"})* 100"
      }
     ]
    },
    {
     "title": "Registry - Memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 9 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",region=\"registry\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{region=\"registry\",kubernetes_io_hostname=~\"^$Node$\"})* 100"
      }
     ]
    },
    {
     "title": "Infra - Memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 9 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",region=\"infra\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{region=\"infra\",kubernetes_io_hostname=~\"^$Node$\"})* 100"
      }
     ]
    },
    {
     "title": "App - Memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",region=\"apps\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{region=\"apps\",kubernetes_io_hostname=~\"^$Node$\"})* 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 14 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 14 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"master\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 14 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\", region=\"master\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 14 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"registry\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 14 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\", region=\"registry\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 16, "y": 14 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"infra\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 14 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\", region=\"infra\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 14 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"apps\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 14 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\", region=\"apps\"})"
      }
     ]
    },
    {
     "title": "Cluster - Root volume filesystem usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Master - Root volume filesystem",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 17 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{region=\"master\",device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{region=\"master\",device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Registry - Root volume filesystem",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 17 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{region=\"registry\",device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{region=\"registry\",device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Infra - Root volume filesystem",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 17 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{region=\"infra\",device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{region=\"infra\",device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "App - Root volume filesystem",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 17 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{region=\"apps\",device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{region=\"apps\",device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 22 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 22 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 22 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"master\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 22 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"master\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 22 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"registry\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 22 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"registry\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 16, "y": 22 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"infra\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 22 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"infra\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 22 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"apps\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 22 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/mapper/VolGroup.*_Root$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"apps\"})"
      }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Master - CPU usage (5m avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",region=\"master\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) / sum (machine_cpu_cores{region=\"master\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Registry - CPU usage (5m avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",region=\"registry\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) / sum (machine_cpu_cores{region=\"registry\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Infra - CPU usage (5m avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",region=\"infra\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) / sum (machine_cpu_cores{region=\"infra\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "App - CPU usage (5m avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",region=\"apps\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) / sum (machine_cpu_cores{region=\"apps\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"master\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\", region=\"master\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"registry\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\", region=\"registry\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"infra\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\", region=\"infra\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"apps\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\", region=\"apps\"})"
    }
   ]
  },
  {
   "title": "Master - CPU usage by host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",region=~\"master\"}[5m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "Registry - CPU usage by host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",region=~\"registry\"}[5m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "Infra - CPU usage by host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{name=~\"^k8s_.*\",region=~\"infra\"}[5m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "App - CPU usage by host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",region=~\"apps\"}[5m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "Master - CPU usage by process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",region=\"master\"}[5m])) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Registry - CPU usage by process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",region=\"registry\"}[5m])) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Infra - CPU usage by process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",region=\"infra\"}[5m])) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "App - CPU usage by process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",region=\"apps\"}[5m])) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Master - CPU usage by namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",region=~\"master\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}[5m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Registry - CPU usage by namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",region=~\"registry\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}[5m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Infra - CPU usage by namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",region=~\"infra\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}[5m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "App - CPU usage by namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",region=~\"apps\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}[5m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Master - CPU usage by Pod|Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",region=\"master\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (container_name, pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    }
   ]
  },
  {
   "title": "Registry - CPU usage by Pod|Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",region=\"registry\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (container_name, pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    }
   ]
  },
  {
   "title": "Infra - CPU usage by Pod|Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",region=\"infra\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (container_name, pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    }
   ]
  },
  {
   "title": "App - CPU usage by Pod|Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",region=\"apps\"}[5m])) by (namespace,container_name, pod_name)",
     "legendFormat": "{{namespace}} | pod: {{ pod_name }} | {{ container_name }}"
    }
   ]
  },
  {
   "title": "Master - CPU usage by container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",region=~\"master\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}[5m])) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Registry - CPU usage by container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 40 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",region=~\"registry\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}[5m])) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Infra - CPU usage by container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",region=~\"infra\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}[5m])) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "App - CPU usage by container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 40 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",region=~\"apps\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}[5m])) by (namespace,container_name)",
     "legendFormat": "{{namespace}} | {{container_name}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Master - Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 48 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",region=\"master\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{region=\"master\",kubernetes_io_hostname=~\"^$Node$\"})* 100"
    }
   ]
  },
  {
   "title": "Registry - Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 48 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",region=\"registry\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{region=\"registry\",kubernetes_io_hostname=~\"^$Node$\"})* 100"
    }
   ]
  },
  {
   "title": "Infra - Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 48 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",region=\"infra\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{region=\"infra\",kubernetes_io_hostname=~\"^$Node$\"})* 100"
    }
   ]
  },
  {
   "title": "App - Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 48 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",region=\"apps\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{region=\"apps\",kubernetes_io_hostname=~\"^$Node$\"})* 100"
    }
   ]
  },
  {
   "title": "Master - Memory usage by host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{id=\"/\",region=\"master\",container_name!=\"POD\"}",
     "legendFormat": "{{instance}}"
    },
    {}
   ]
  },
  {
   "title": "Registry - Memory usage by host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{id=\"/\",region=\"registry\",container_name!=\"POD\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Infra - Memory usage by host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{id=\"/\",region=\"infra\",container_name!=\"POD\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "App - Memory usage by host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{id=\"/\",region=\"apps\",container_name!=\"POD\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Master - Processes memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",region=\"master\"}) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Registry - Processes memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",region=\"registry\"}) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Infra - Processes memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",region=\"infra\"}) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "App - Processes memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",region=\"apps\"}) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Master - Memory usage by namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",region=\"master\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Registry - Memory usage by namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",region=\"registry\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Infra - Memory usage by namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",region=\"infra\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "App - Memory usage by namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",region=\"apps\",container_name!=\"POD\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Master - Memory usage by pod:container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",region=\"master\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}) by (container_name,pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    }
   ]
  },
  {
   "title": "Registry - Memory usage by pod:container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 72 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",region=\"registry\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}) by (container_name,pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    }
   ]
  },
  {
   "title": "Infra - Memory usage by pod:container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",region=\"infra\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}) by (container_name,pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    }
   ]
  },
  {
   "title": "App - Memory usage by pod:container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 72 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",region=\"apps\",container_name!=\"POD\"}) by (namespace,container_name,pod_name)",
     "legendFormat": "{{namespace}} | pod: {{ pod_name }} | {{ container_name }}"
    }
   ]
  },
  { "title": "File system", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Master - Root volume filesystem",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 79 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{region=\"master\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{region=\"master\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Registry - Root volume filesystem",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 79 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{region=\"registry\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{region=\"registry\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Infra - Root volume filesystem",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 79 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{region=\"infra\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{region=\"infra\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "App - Root volume filesystem",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 79 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{region=\"apps\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{region=\"apps\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used Root Volume",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 84 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"master\"})"
    }
   ]
  },
  {
   "title": "Total Root Volume",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 84 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"master\"})"
    }
   ]
  },
  {
   "title": "Used Root Volume",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 84 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"registry\"})"
    }
   ]
  },
  {
   "title": "Total Root Volume",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 84 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"registry\"})"
    }
   ]
  },
  {
   "title": "Used Root Volume",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 84 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"infra\"})"
    }
   ]
  },
  {
   "title": "Total Root Volume",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 84 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"infra\"})"
    }
   ]
  },
  {
   "title": "Used Root Volume",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 84 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"apps\"})"
    }
   ]
  },
  {
   "title": "Total Root Volume",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 84 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\", region=\"apps\"})"
    }
   ]
  },
  {
   "title": "Master - Root volume file system",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{region=\"master\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\"}",
     "legendFormat": "Usage: {{instance}}"
    },
    {
     "expr": "container_fs_limit_bytes{region=\"master\",device=~\"^/dev/mapper/VolGroup.*_Root\"}",
     "legendFormat": "Limit: {{instance}}"
    }
   ]
  },
  {
   "title": "Registry - Root volume file system",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 87 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{region=\"registry\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\"}",
     "legendFormat": "Usage: {{instance}}"
    },
    {
     "expr": "container_fs_limit_bytes{region=\"registry\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\"}",
     "legendFormat": "Limit: {{instance}}"
    }
   ]
  },
  {
   "title": "Infra - Root volume file system",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{region=\"infra\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\"}",
     "legendFormat": "Usage: {{instance}}"
    }
   ]
  },
  {
   "title": "App - Root volume file system",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 87 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{region=\"apps\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\"}",
     "legendFormat": "Usage: {{instance}}"
    },
    {
     "expr": "container_fs_limit_bytes{region=\"apps\",device=~\"^/dev/mapper/VolGroup.*_Root\",id=\"/\"}",
     "legendFormat": "Limit: {{instance}}"
    }
   ]
  },
  {
   "title": "Master - Var01 file system",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{region=\"master\",device=~\"^/dev/mapper/VolGroup.*_Var01\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}",
     "legendFormat": "Usage: {{instance}}"
    },
    {
     "expr": "container_fs_limit_bytes{region=\"master\",device=~\"^/dev/mapper/VolGroup.*_Var01\",kubernetes_io_hostname=~\"^$Node$\"}",
     "legendFormat": "Limit: {{instance}}"
    }
   ]
  },
  {
   "title": "Registry - Var01 file system",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 93 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{region=\"registry\",device=~\"^/dev/mapper/VolGroup.*_Var01\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}",
     "legendFormat": "Usage: {{instance}}"
    },
    {
     "expr": "container_fs_limit_bytes{region=\"registry\",device=~\"^/dev/mapper/VolGroup.*_Var01\",kubernetes_io_hostname=~\"^$Node$\"}",
     "legendFormat": "Limit: {{instance}}"
    }
   ]
  },
  {
   "title": "Infra - Var01 file system",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{region=\"infra\",device=~\"^/dev/mapper/VolGroup.*_Var01\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}",
     "legendFormat": "Usage: {{instance}}"
    },
    {
     "expr": "container_fs_limit_bytes{region=\"infra\",device=~\"^/dev/mapper/VolGroup.*_Var01\",kubernetes_io_hostname=~\"^$Node$\"}",
     "legendFormat": "Limit: {{instance}}"
    }
   ]
  },
  {
   "title": "Registry - Var01 file system",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 93 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{region=\"registry\",device=~\"^/dev/mapper/VolGroup.*_Var01\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}",
     "legendFormat": "Usage: {{instance}}"
    },
    {
     "expr": "container_fs_limit_bytes{region=\"registry\",device=~\"^/dev/mapper/VolGroup.*_Var01\",kubernetes_io_hostname=~\"^$Node$\"}",
     "legendFormat": "Limit: {{instance}}"
    }
   ]
  },
  {
   "title": "Master - Var02 file system",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{region=\"master\",device=~\"^/dev/mapper/VolGroup.*_Var02\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}",
     "legendFormat": "Usage: {{instance}}"
    },
    {
     "expr": "container_fs_limit_bytes{region=\"master\",device=~\"^/dev/mapper/VolGroup.*_Var02\",kubernetes_io_hostname=~\"^$Node$\"}",
     "legendFormat": "Limit: {{instance}}"
    }
   ]
  },
  {
   "title": "Registry - Var02 file system",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 99 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{region=\"registry\",device=~\"^/dev/mapper/VolGroup.*_Var02\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}",
     "legendFormat": "Usage: {{instance}}"
    },
    {
     "expr": "container_fs_limit_bytes{region=\"registry\",device=~\"^/dev/mapper/VolGroup.*_Var02\",kubernetes_io_hostname=~\"^$Node$\"}",
     "legendFormat": "Limit: {{instance}}"
    }
   ]
  },
  {
   "title": "Infra - Var02 file system",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{region=\"infra\",device=~\"^/dev/mapper/VolGroup.*_Var02\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}",
     "legendFormat": "Usage: {{instance}}"
    },
    {
     "expr": "container_fs_limit_bytes{region=\"infra\",device=~\"^/dev/mapper/VolGroup.*_Var02\",kubernetes_io_hostname=~\"^$Node$\"}",
     "legendFormat": "Limit: {{instance}}"
    }
   ]
  },
  {
   "title": "App - Var02 file system",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 99 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{region=\"apps\",device=~\"^/dev/mapper/VolGroup.*_Var02\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}",
     "legendFormat": "Usage: {{instance}}"
    },
    {
     "expr": "container_fs_limit_bytes{region=\"apps\",device=~\"^/dev/mapper/VolGroup.*_Var02\",kubernetes_io_hostname=~\"^$Node$\"}",
     "legendFormat": "Limit: {{instance}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Cluster - Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[5m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Master - Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 106 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\", region=\"master\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\", region=\"master\"}[5m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Registry - Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 106 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\", region=\"registry\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\", region=\"registry\"}[5m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Infra - Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 106 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\", region=\"infra\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\", region=\"infra\"}[5m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "App - Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 106 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\", region=\"apps\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\", region=\"apps\"}[5m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "All processes network I/O (5m avg)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (id)",
     "legendFormat": "-> {{ id }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (id)",
     "legendFormat": "<- {{ id }}"
    }
   ]
  },
  {
   "title": "Master - Processes network I/O (5m avg)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",region=\"master\"}[5m])) by (id)",
     "legendFormat": "-> {{ id }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",region=\"master\"}[5m])) by (id)",
     "legendFormat": "<- {{ id }}"
    }
   ]
  },
  {
   "title": "Registry - Processes network I/O (5m avg)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",region=\"registry\"}[5m])) by (id)",
     "legendFormat": "-> {{ id }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",region=\"registry\"}[5m])) by (id)",
     "legendFormat": "<- {{ id }}"
    }
   ]
  },
  {
   "title": "Infra - Processes network I/O (5m avg)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 150 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",region=\"infra\"}[5m])) by (id)",
     "legendFormat": "-> {{ id }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",region=\"infra\"}[5m])) by (id)",
     "legendFormat": "<- {{ id }}"
    }
   ]
  },
  {
   "title": "App - Processes network I/O (5m avg)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 163 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",region=\"apps\"}[5m])) by (id)",
     "legendFormat": "-> {{ id }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\",region=\"apps\"}[5m])) by (id)",
     "legendFormat": "<- {{ id }}"
    }
   ]
  },
  {
   "title": "Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 176 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application Pod limit",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 84 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "1/((sum(machine_cpu_cores{region!=\"master\",region!=\"infra\"})*10) / sum(kubelet_running_pod_count))  * 100 "
      }
     ]
    },
    {
     "title": "Maximum Number of Pods allowed on App Nodes",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 5, "x": 13, "y": 84 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(machine_cpu_cores{region!=\"master\",region!=\"infra\"})*10"
      }
     ]
    },
    {
     "title": "Current number of Running App Pods",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 84 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kubelet_running_pod_count{region!=\"master\",region!=\"infra\"})"
      }
     ]
    },
    {
     "title": "Pods per node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (kubelet_running_pod_count) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Pods CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (namespace,pod_name)",
       "legendFormat": "{{namespace}}->{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Pods memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}) by (namespace,pod_name)",
       "legendFormat": "{{namespace}}->{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Pods network I/O (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (namespace,pod_name)",
       "legendFormat": "{{namespace}}-> {{ pod_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (namespace,pod_name)",
       "legendFormat": "{{namespace}}<- {{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 177 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers per node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (kubelet_running_container_count) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Containers CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"$Node$\"}[5m])) by (namespace,container_name, pod_name)",
       "legendFormat": "{{namespace}}->pod: {{ pod_name }} | {{ container_name }}"
      }
     ]
    },
    {
     "title": "Containers memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 99 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}) by (namespace,container_name, pod_name)",
       "legendFormat": "{{namespace}}->pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}) by (namespace,kubernetes_io_hostname, name, image)",
       "legendFormat": "{{namespace}}->docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}) by (namespace,kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "{{namespace}}->rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      }
     ]
    },
    {
     "title": "Containers network I/O (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 106 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (namespace,container_name, pod_name)",
       "legendFormat": "{{namespace}}-> pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (namespace,container_name, pod_name)",
       "legendFormat": "{{namespace}}<- pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (namespace,kubernetes_io_hostname, name, image)",
       "legendFormat": "{{namespace}}-> docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (namespace,kubernetes_io_hostname, name, image)",
       "legendFormat": "{{namespace}}<- docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (namespace,kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "{{namespace}}-> rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (namespace,kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "{{namespace}}<- rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  }
 ]
}